const ExampleList = [
  {
    imageAlt: "product1",
    imageSrc: ["/Images/card1.jpeg"],
    name: "bag 1",
    price: "215",
    colors: ["red", "blue", "black"],
    id: 0,
    category: "bag",
  },
  {
    imageAlt: "product2",
    imageSrc: ["/Images/card2.jpg"],
    name: "bag 2",
    price: "165",
    colors: ["red", "blue", "black"],
    id: 1,
    category: "bag",
  },
  {
    imageAlt: "product3",
    imageSrc: ["/Images/card3.jpg"],
    name: "bag 3",
    price: "127",
    colors: ["red", "blue", "black"],
    id: 2,
    category: "bag",
  },
  {
    imageAlt: "product4",
    imageSrc: ["/Images/card4.jpg", "/Images/card3.jpg"],
    name: "bag 4",
    price: "100",
    colors: ["red", "blue", "black"],
    id: 3,
    category: "bag",
  },
  {
    imageAlt: "product5",
    imageSrc: ["/Images/card5.jpg"],
    name: "bag 5",
    price: "79",
    colors: ["red", "blue", "black"],
    id: 4,
    category: "bag",
  },
  {
    imageAlt: "product5",
    imageSrc: ["/Images/card6.jpg"],
    name: "bag 6",
    price: "79",
    colors: ["red", "blue", "black"],
    id: 5,
    category: "bag",
  },
  {
    imageAlt: "product1",
    imageSrc: ["/Images/card1.jpeg"],
    name: "bag 1",
    price: "215",
    colors: ["red", "blue", "black"],
    id: 6,
    category: "bag",
  },
  {
    imageAlt: "product2",
    imageSrc: ["/Images/card2.jpg"],
    name: "bag 2",
    price: "165",
    colors: ["red", "blue", "black"],
    id: 7,
    category: "bag",
  },
  {
    imageAlt: "product3",
    imageSrc: ["/Images/card3.jpg"],
    name: "bag 3",
    price: "127",
    colors: ["red", "blue", "black"],
    id: 8,
    category: "bag",
  },
  {
    imageAlt: "product4",
    imageSrc: ["/Images/card4.jpg", "/Images/card3.jpg"],
    name: "bag 4",
    price: "100",
    colors: ["red", "blue", "black"],
    id: 9,
    category: "bag",
  },
  {
    imageAlt: "product5",
    imageSrc: ["/Images/card5.jpg"],
    name: "bag 5",
    price: "79",
    colors: ["red", "blue", "black"],
    id: 10,
    category: "bag",
  },
  {
    imageAlt: "product5",
    imageSrc: ["/Images/card6.jpg"],
    name: "bag 6",
    price: "79",
    colors: ["red", "blue", "black"],
    id: 11,
    category: "bag",
  },
  {
    imageAlt: "product1",
    imageSrc: ["/Images/card1.jpeg"],
    name: "bag 1",
    price: "215",
    colors: ["red", "blue", "black"],
    id: 12,
    category: "bag",
  },
  {
    imageAlt: "product2",
    imageSrc: ["/Images/card2.jpg"],
    name: "bag 2",
    price: "165",
    colors: ["red", "blue", "black"],
    id: 13,
    category: "bag",
  },
  {
    imageAlt: "product3",
    imageSrc: ["/Images/card3.jpg"],
    name: "bag 3",
    price: "127",
    colors: ["red", "blue", "black"],
    id: 14,
    category: "bag",
  },
  {
    imageAlt: "product4",
    imageSrc: ["/Images/card4.jpg", "/Images/card3.jpg"],
    name: "bag 4",
    price: "100",
    colors: ["red", "blue", "black"],
    id: 15,
    category: "bag",
  },
  {
    imageAlt: "product5",
    imageSrc: ["/Images/card5.jpg"],
    name: "bag 5",
    price: "79",
    colors: ["red", "blue", "black"],
    id: 16,
    category: "bag",
  },
  {
    imageAlt: "product5",
    imageSrc: ["/Images/card6.jpg"],
    name: "bag 6",
    price: "79",
    colors: ["red", "blue", "black"],
    id: 17,
    category: "bag",
  },
];

export default ExampleList;
